# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftWithMVVM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftWithMVVM

pod 'SnapKit','~> 4.0.0'
pod 'Alamofire'
pod ‘HandyJSON’
pod 'RxSwift'
pod 'RxCocoa'
pod 'Kingfisher'
pod 'Moya/RxSwift'

end
